<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'WebinoDbDump\Module'                                => __DIR__ . '/Module.php',
  'WebinoDbDump\Db\Sql\FileInterface'                  => __DIR__ . '/Db/Sql/FileInterface.php',
  'WebinoDbDump\Db\Sql\File'                           => __DIR__ . '/Db/Sql/File.php',
  'WebinoDbDump\Db\Dump\Table\AbstractTable'           => __DIR__ . '/Db/Dump/Table/AbstractTable.php',
  'WebinoDbDump\Db\Dump\Table\TriggersInterface'       => __DIR__ . '/Db/Dump/Table/TriggersInterface.php',
  'WebinoDbDump\Db\Dump\Table\AbstractColumns'         => __DIR__ . '/Db/Dump/Table/AbstractColumns.php',
  'WebinoDbDump\Db\Dump\Table\ColumnsInterface'        => __DIR__ . '/Db/Dump/Table/ColumnsInterface.php',
  'WebinoDbDump\Db\Dump\Table\AbstractTriggers'        => __DIR__ . '/Db/Dump/Table/AbstractTriggers.php',
  'WebinoDbDump\Db\Dump\DumpInterface'                 => __DIR__ . '/Db/Dump/DumpInterface.php',
  'WebinoDbDump\Db\Dump\Platform\AbstractPlatform'     => __DIR__ . '/Db/Dump/Platform/AbstractPlatform.php',
  'WebinoDbDump\Db\Dump\Platform\Mysql\Table\Columns'  => __DIR__ . '/Db/Dump/Platform/Mysql/Table/Columns.php',
  'WebinoDbDump\Db\Dump\Platform\Mysql\Table\Table'    => __DIR__ . '/Db/Dump/Platform/Mysql/Table/Table.php',
  'WebinoDbDump\Db\Dump\Platform\Mysql\Table\Triggers' => __DIR__ . '/Db/Dump/Platform/Mysql/Table/Triggers.php',
  'WebinoDbDump\Db\Dump\Platform\Mysql\Mysql'          => __DIR__ . '/Db/Dump/Platform/Mysql/Mysql.php',
  'WebinoDbDump\Db\Dump\Platform\PlatformInterface'    => __DIR__ . '/Db/Dump/Platform/PlatformInterface.php',
  'WebinoDbDump\Db\Dump\Adapter'                       => __DIR__ . '/Db/Dump/Adapter.php',
  'WebinoDbDump\Db\Dump\Dump'                          => __DIR__ . '/Db/Dump/Dump.php',
);
